name: Shell Checking

on: [pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    
    - name: shellcheck
      uses: ludeeus/action-shellcheck@0.1.0
    - name: shellcheck
  
